### ISSUE TITLE
FCM or APNS for iOS

### ISSUE THREAD

**Issue by hardikamal** [aerogear/aerogear-ios-push-objc#6]
Hi,

Is this integrated with fcm for ios or apns?

Thanks

**Comment by danielpassos** [comment]
Hey @hardikamal,

Not yet, but I really like to FCM to the [Unified Push Service](https://github.com/aerogear/aerogear-unifiedpush-server/)

Do you wanna open a JIRA for it?

https://issues.jboss.org/projects/AGIOS/

**Comment by hardikamal** [comment]
Hi @danielpassos,

Done. https://issues.jboss.org/browse/AGIOS-605

**Comment by danielpassos** [comment]
@hardikamal Thanks, I'm going to close this, and move whatever update about this to [AGIOS-605](https://issues.jboss.org/browse/AGIOS-605)

**Comment by hardikamal** [comment]
Hi @danielpassos Any update on this?

**Comment by danielpassos** [comment]
@hardikamal It is not on our roadmap. Feel free to make some noise about it on [Mailing list](https://groups.google.com/forum/#!forum/aerogear) or in the [AEROGEAR-3255](https://issues.jboss.org/browse/AEROGEAR-3255)
